spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/video_shop?characterEncoding=utf-8&useSSL=false
    username: root
    password: Qq83659757
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: product
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.3:8761/eureka/
server:
  port: 18081
